# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-17 00:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 17, 3, 11, 41, 443943), verbose_name='Опубликовано'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
